service:
  name: serverless-s3-trigger-nodejs

provider:
  name: aws
  stage: ${opt:stage,'dev'}
  runtime: nodejs10.x

package:
  excludeDevDependencies: true
  exclude:
    - env/**
    - test/**

custom:
  envPath: "env/.${self:provider.stage}_env.json"

functions:
  hello:
    handler: dist/src/lambda.trigger
    events:
      - s3:
          bucket: ${file(${self:custom.envPath}):UPLOAD_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
          existing: true
