service:
  name: serverless-s3-trigger-nodejs

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          method: get
          path: hello
