service:
  name: serverless-s3-trigger-nodejs

custom:
  envPath: "env/.${self:provider.stage}_env.json"

provider:
  name: aws
  stage: ${opt:stage,'dev'}
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "*"
package:
  # excludeDevDependencies: true
  exclude:
    - env/**
    - test/**
    - "**/*.spec.js"

functions:
  hello:
    handler: src/lambda.trigger
    environment:
      DESTINATION_BUCKET_NAME: ${file(${self:custom.envPath}):DESTINATION_BUCKET_NAME}
      API_BASE_URI: ${file(${self:custom.envPath}):API_BASE_URI}
    events:
      - s3:
          bucket: ${file(${self:custom.envPath}):UPLOAD_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
          existing: true
